# 4a)

In [37]:
import numpy as np
from numpy.linalg import inv

In [38]:
def normalEquationRegression(X, Y):
    xt = X.transpose()
    b = np.ones((1,xt.shape[1]))
    xt2 = np.vstack((b,xt))
    x = xt2.transpose()
    print(xt2)
    print(x)
    n1=np.matmul(xt2,x)
    n2=inv(n1)
    n3=np.matmul(n2,xt2)
    n4= np.matmul(n3,Y)
    return n4
    

In [39]:
m = np.matrix([[2104,5,1,45],[1416,3,2,40],[1534,3,2,30],[852,2,1,36]])
m

matrix([[2104,    5,    1,   45],
        [1416,    3,    2,   40],
        [1534,    3,    2,   30],
        [ 852,    2,    1,   36]])

In [40]:
n = np.matrix([[460],[232],[315],[178]])

In [41]:
normalEquationRegression(m,n)

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [2.104e+03 1.416e+03 1.534e+03 8.520e+02]
 [5.000e+00 3.000e+00 3.000e+00 2.000e+00]
 [1.000e+00 2.000e+00 2.000e+00 1.000e+00]
 [4.500e+01 4.000e+01 3.000e+01 3.600e+01]]
[[1.000e+00 2.104e+03 5.000e+00 1.000e+00 4.500e+01]
 [1.000e+00 1.416e+03 3.000e+00 2.000e+00 4.000e+01]
 [1.000e+00 1.534e+03 3.000e+00 2.000e+00 3.000e+01]
 [1.000e+00 8.520e+02 2.000e+00 1.000e+00 3.600e+01]]


matrix([[-648.7890625 ],
        [   0.79418945],
        [-110.09375   ],
        [ -74.0703125 ],
        [  -3.69091797]])

# 4b)

In [51]:
def graient_descent(x,y):
    mcurr=bcurr=0
    n=len(x)
    iterations = 1000
    learningrate=0.001
    for i in range(0,10000):
        print(mcurr,bcurr,i)
        y_predicted= x*mcurr+bcurr
        md= -(2/n)*sum(x*(y-y_predicted))
        bd= -(2/n)*sum(y-y_predicted)
        mcurr=mcurr - md*learningrate
        bcurr=bcurr - bd*learningrate

In [49]:
x=np.array([1,3,6])
y=np.array([3,7,13])

In [50]:
graient_descent(x,y)

0 0 0
0.068 0.015333333333333332 1
0.13381244444444446 0.030182666666666667 2
0.19750764503703705 0.0445635517037037 3
0.25915365357787656 0.058491040300049375 4
0.318816334599488 0.0719797005289301 5
0.3765594356682442 0.08504363223054232 6
0.4324446554262144 0.09769648206162627 7
0.48653170944606633 0.10995145806132826 8
0.5388783939693115 0.1218213437488985 9
0.5895406475959266 0.13331851176827195 10
0.6385726109911964 0.1444549370940959 11
0.6860266846735058 0.15524220981329973 12
0.7319535849447629 0.16569154749584974 13
0.7764023980231511 0.17581380716789297 14
0.8194206324359885 0.1856194969000695 15
0.8610542697286178 0.19511878702336277 16
0.9013478135434511 0.2043215209844586 17
0.9403443371215555 0.2132372258522 18
0.9780855292774798 0.2218751224863519 19
1.0146117388963947 0.23024413537952934 20
1.0499620180010416 0.2383529021827943 21
1.0841741634344577 0.24620978292508844 22
1.1172847572029672 0.25382286893634187 23
1.1493292055225006 0.26119999148378276 24
1.180341776609

2.0883913739497393 0.6003663886393767 543
2.0883449292243514 0.6005763800357664 544
2.0882985088612327 0.6007862610808659 545
2.088252112848949 0.6009960318329626 546
2.0882057411760284 0.6012056923503036 547
2.0881593938309617 0.6014152426910961 548
2.088113070802205 0.6016246829135076 549
2.0880667720781805 0.6018340130756659 550
2.0880204976472787 0.60204323323566 551
2.0879742474978578 0.6022523434515401 552
2.0879280216182465 0.602461343781318 553
2.087881819996745 0.6026702342829671 554
2.087835642621625 0.6028790150144229 555
2.0877894894811324 0.6030876860335832 556
2.087743360563487 0.6032962473983084 557
2.087697255856885 0.6035046991664219 558
2.0876511753494977 0.6037130413957098 559
2.087605119029475 0.6039212741439217 560
2.087559086884945 0.6041293974687707 561
2.0875130789040153 0.6043374114279335 562
2.0874670950747727 0.6045453160790509 563
2.087421135385286 0.6047531114797277 564
2.087375199823606 0.604960797687533 565
2.087329288377765 0.6051683747600005 566
2.08728

# 4 c

In [10]:
import autograd.numpy as np  # Thinly-wrapped numpy
from autograd import grad, jacobian   # The only autograd function you may ever need
def diff(y_predicted):
    y = np.array([[2],[3],[4],[5]])
    return (y-y_predicted)*(y-y_predicted)

def gradient_descent(X,y, alpha):
    theta1=0
    theta0=0
    n=len(X)
    iterations = 3
    grad_theta=jacobian(diff)
        
    for i in range(0,iterations):
        print('Value of theta 0 and theta1 at iteration',i,theta1,theta0)
        #print(theta0, theta1, i)
        y_predicted= X*theta1+theta0
        bd=grad_theta(diff(y_predicted))
        md=grad_theta(diff(y_predicted))
        theta1=(theta1 - md*alpha)
        theta0=(theta0 - bd*alpha)  
X = np.array([[1, 3], [2, 9],[3,6],[4,8]])
y = np.array([[2],[3],[4],[5]])
alpha=0.1
gradient_descent(X,y,alpha)

Value of theta 0 and theta1 at iteration 0 0 0
Value of theta 0 and theta1 at iteration 1 [[[[-0.4  0. ]
   [ 0.   0. ]
   [ 0.   0. ]
   [ 0.   0. ]]

  [[ 0.  -0.4]
   [ 0.   0. ]
   [ 0.   0. ]
   [ 0.   0. ]]]


 [[[ 0.   0. ]
   [-1.2  0. ]
   [ 0.   0. ]
   [ 0.   0. ]]

  [[ 0.   0. ]
   [ 0.  -1.2]
   [ 0.   0. ]
   [ 0.   0. ]]]


 [[[ 0.   0. ]
   [ 0.   0. ]
   [-2.4  0. ]
   [ 0.   0. ]]

  [[ 0.   0. ]
   [ 0.   0. ]
   [ 0.  -2.4]
   [ 0.   0. ]]]


 [[[ 0.   0. ]
   [ 0.   0. ]
   [ 0.   0. ]
   [-4.   0. ]]

  [[ 0.   0. ]
   [ 0.   0. ]
   [ 0.   0. ]
   [ 0.  -4. ]]]] [[[[-0.4  0. ]
   [ 0.   0. ]
   [ 0.   0. ]
   [ 0.   0. ]]

  [[ 0.  -0.4]
   [ 0.   0. ]
   [ 0.   0. ]
   [ 0.   0. ]]]


 [[[ 0.   0. ]
   [-1.2  0. ]
   [ 0.   0. ]
   [ 0.   0. ]]

  [[ 0.   0. ]
   [ 0.  -1.2]
   [ 0.   0. ]
   [ 0.   0. ]]]


 [[[ 0.   0. ]
   [ 0.   0. ]
   [-2.4  0. ]
   [ 0.   0. ]]

  [[ 0.   0. ]
   [ 0.   0. ]
   [ 0.  -2.4]
   [ 0.   0. ]]]


 [[[ 0.   0. ]
   [ 0.   0. ]